apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clo835-fp
  region: us-east-1
  version: "1.31"

availabilityZones:
  - us-east-1a
  - us-east-1b

iam:
  serviceRoleARN: arn:aws:iam::656725130383:role/LabRole

managedNodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    ssh:
      enableSsm: true
    iam:
      instanceRoleARN: arn:aws:iam::656725130383:role/LabRole