apiVersion: v1
kind: Namespace
metadata:
  name: fp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clo835_sa
  namespace: fp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: CLO835
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clo835-role-binding
subjects:
  - kind: ServiceAccount
    name: clo835_sa
    namespace: fp
roleRef:
  kind: ClusterRole
  name: CLO835
  apiGroup: rbac.authorization.k8s.io
