apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: fp
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
